"""
Scrapes to gather semester date information and saves it to ACADEMIC_CALENDAR_FILE
Pull request required once every year/two years. However,
feel free to change it so it logs to the database automatically
"""

import requests

CALENDAR_URL: str = "https://about.uq.edu.au/academic-calendar"
ACADEMIC_CALENDAR_FILE: str = "uqcsbot/static/academic_calendar.html"


def _scrape_to_file() -> None:
    # Scrapes the website and saves it to ACADEMIC_CALENDAR_FILE

    calendar_page = requests.get(CALENDAR_URL)
    if calendar_page.status_code != requests.codes.ok:
        raise RuntimeError(
            f"Failed to fetch calendar page: {calendar_page.status_code}"
        )

    with open(ACADEMIC_CALENDAR_FILE, "w", encoding="utf-8") as file:
        file.write("<!-- Generated by uqcsbot/utils/whatweekisit_utils.py -->\n")
        file.write(calendar_page.text)


# Run the script itself to update the file
if __name__ == "__main__":
    _scrape_to_file()
