name: Code Style Check

on: [ pull_request ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run black
        id: runBlack
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./uqcsbot"
          version: "23.12.1"

      - name: Convert logs to artifacts
        uses: actions/upload-artifact@v4
        if: always() && (steps.runBlack.outcome == 'failure')
        with:
          name: "black-logs"
          path: "/tmp/blk_*"
          