name: Static Code Tests

on:
  push:
    branches: [ main ]
  pull_request: []

env: 
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.4.2'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-python.yml
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
        
      - name: Check with pytest
        run: poetry run pytest

  types:
    name: Run typechecking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-python.yml
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Check with pyright
        run: poetry run pyright uqcsbot